# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{babelabel}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["marceljackwerth@gmail.com"]
  s.date = %q{2011-08-29}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{marcel@northdocks.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/babelabel/application_controller.rb",
    "app/controllers/babelabel/assets_controller.rb",
    "app/controllers/babelabel/translations_controller.rb",
    "app/views/babelabel/assets/site.css.less",
    "app/views/babelabel/layouts/babelabel.html.haml",
    "app/views/babelabel/translations/_dialogs.html.haml",
    "app/views/babelabel/translations/_topbar.html.haml",
    "app/views/babelabel/translations/_translation_popout.html.haml",
    "app/views/babelabel/translations/_translation_row.html.haml",
    "app/views/babelabel/translations/index.html.haml",
    "babelabel.gemspec",
    "config/routes.rb",
    "lib/babelabel.rb",
    "lib/babelabel/engine.rb",
    "lib/babelabel/mongo_backend.rb",
    "lib/babelabel/mongo_writeback.rb",
    "public/images/babelabel/favicon.png",
    "public/images/babelabel/flags/de.png",
    "public/images/babelabel/flags/en.png",
    "public/images/babelabel/spinner.gif",
    "public/images/babelabel/translation-hide.png",
    "public/images/babelabel/translation-popout.png",
    "public/images/babelabel/translation-unhide.png",
    "public/images/babelabel/validation-alert.png",
    "public/images/babelabel/validation-ok.png",
    "public/javascripts/babelabel/iso8601.js",
    "public/javascripts/babelabel/jquery-ui.js",
    "public/javascripts/babelabel/jquery.js",
    "public/javascripts/babelabel/jquery.timeago.js",
    "public/javascripts/babelabel/jquery.tmpl.js",
    "public/javascripts/babelabel/knockout-1.2.1.js",
    "public/javascripts/babelabel/underscore.js",
    "public/javascripts/babelabel/underscore.string.js",
    "public/stylesheets/babelabel/bootstrap.css",
    "spec/babelabel_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/sirlantis/babelabel}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{TODO: one-line summary of your gem}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<less>, [">= 2.0.6"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<less>, [">= 2.0.6"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<less>, [">= 2.0.6"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

